In [1]:
# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import recall_score,classification_report,accuracy_score,precision_score,f1_score,roc_auc_score,roc_curve
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from datetime import datetime
import math
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer

In [2]:
df_1=pd.read_csv("gps_data_tabular.csv")
df_1.head()

            Time   Latitude  Longitude     Speed  Accuracy  Partition
0  1522242002000  23.154500  72.668081  0.000000      10.0          0
1  1522242099000  23.154457  72.668187  0.000000      10.5          1
2  1522242102000  23.154471  72.668257  0.096768      10.0          0
3  1522242103000  23.154438  72.668264  0.279494      10.0          0
4  1522242105000  23.154411  72.668269  0.000000      10.0          0

In [3]:
df_2=pd.read_csv("gps_data_1_tabular.csv")
df_2.head()

            Time   Latitude  Longitude  Speed    Accuracy  Partition
0  1522847094212  23.156355  72.664453    NaN  899.999023          0
1  1522847099542  23.155736  72.661405   3.86   19.000000          0
2  1522847100544  23.155756  72.661394   4.48   27.000000          0
3  1522847101289  23.155797  72.661301   4.79   20.000000          0
4  1522847102000  23.155811  72.661276   4.76   19.000000          0

In [4]:
df_1.columns

Index(['Time', 'Latitude', 'Longitude', 'Speed', 'Accuracy', 'Partition'], dtype='object')

In [5]:
df_2.columns

Index(['Time', 'Latitude', 'Longitude', 'Speed', 'Accuracy', 'Partition'], dtype='object')

In [6]:
df_merged=pd.concat([df_1,df_2],ignore_index=True)

In [7]:
print("--- Merged DataFrame from CSV files ---")
print(df_merged.head())

--- Merged DataFrame from CSV files ---
            Time   Latitude  Longitude     Speed  Accuracy  Partition
0  1522242002000  23.154500  72.668081  0.000000      10.0          0
1  1522242099000  23.154457  72.668187  0.000000      10.5          1
2  1522242102000  23.154471  72.668257  0.096768      10.0          0
3  1522242103000  23.154438  72.668264  0.279494      10.0          0
4  1522242105000  23.154411  72.668269  0.000000      10.0          0

In [8]:
df_merged.head()

            Time   Latitude  Longitude     Speed  Accuracy  Partition
0  1522242002000  23.154500  72.668081  0.000000      10.0          0
1  1522242099000  23.154457  72.668187  0.000000      10.5          1
2  1522242102000  23.154471  72.668257  0.096768      10.0          0
3  1522242103000  23.154438  72.668264  0.279494      10.0          0
4  1522242105000  23.154411  72.668269  0.000000      10.0          0

In [9]:
#df_merged.to_csv('Final_Dataset.csv')

In [10]:
# Convert Unix epoch (milliseconds) to datetime
df_merged['datetime'] = pd.to_datetime(df_merged['Time'], unit='ms')
df_merged['date'] = df_merged['datetime'].dt.date
df_merged['time_hms'] = df_merged['datetime'].dt.time

In [11]:
df_merged.head()

,Time,Latitude,Longitude,Speed,Accuracy,Partition,datetime,date,time_hms
0,1522242002000,23.154500,72.668081,0.000000,10.0,0,2018-03-28 13:00:02,2018-03-28,13:00:02
1,1522242099000,23.154457,72.668187,0.000000,10.5,1,2018-03-28 13:01:39,2018-03-28,13:01:39
2,1522242102000,23.154471,72.668257,0.096768,10.0,0,2018-03-28 13:01:42,2018-03-28,13:01:42
3,1522242103000,23.154438,72.668264,0.279494,10.0,0,2018-03-28 13:01:43,2018-03-28,13:01:43
4,1522242105000,23.154411,72.668269,0.000000,10.0,0,2018-03-28 13:01:45,2018-03-28,13:01:45

In [12]:
df_merged['hour'] = df_merged['datetime'].dt.hour
df_merged['minute'] = df_merged['datetime'].dt.minute  
df_merged['second'] = df_merged['datetime'].dt.second
df_merged['day_of_week'] = df_merged['datetime'].dt.dayofweek
df_merged['day_of_year'] = df_merged['datetime'].dt.dayofyear

In [13]:
df_merged.head()

,Time,Latitude,Longitude,Speed,Accuracy,Partition,datetime,date,time_hms,hour,minute,second,day_of_week,day_of_year
0,1522242002000,23.154500,72.668081,0.000000,10.0,0,2018-03-28 13:00:02,2018-03-28,13:00:02,13,0,2,2,87
1,1522242099000,23.154457,72.668187,0.000000,10.5,1,2018-03-28 13:01:39,2018-03-28,13:01:39,13,1,39,2,87
2,1522242102000,23.154471,72.668257,0.096768,10.0,0,2018-03-28 13:01:42,2018-03-28,13:01:42,13,1,42,2,87
3,1522242103000,23.154438,72.668264,0.279494,10.0,0,2018-03-28 13:01:43,2018-03-28,13:01:43,13,1,43,2,87
4,1522242105000,23.154411,72.668269,0.000000,10.0,0,2018-03-28 13:01:45,2018-03-28,13:01:45,13,1,45,2,87

In [14]:
# Time-based numerical features
df_merged['hour_sin'] = np.sin(2 * np.pi * df_merged['hour'] / 24)
df_merged['hour_cos'] = np.cos(2 * np.pi * df_merged['hour'] / 24)
df_merged['minute_sin'] = np.sin(2 * np.pi * df_merged['minute'] / 60)
df_merged['minute_cos'] = np.cos(2 * np.pi * df_merged['minute'] / 60)

# Time since start of dataset
df_merged['time_elapsed_seconds'] = (df_merged['datetime'] - df_merged['datetime'].min()).dt.total_seconds()
df_merged['time_elapsed_minutes'] = df_merged['time_elapsed_seconds'] / 60
df_merged['time_elapsed_hours'] = df_merged['time_elapsed_seconds'] / 3600

In [15]:
df_merged.head()

,Time,Latitude,Longitude,Speed,Accuracy,Partition,datetime,date,time_hms,hour,...,second,day_of_week,day_of_year,hour_sin,hour_cos,minute_sin,minute_cos,time_elapsed_seconds,time_elapsed_minutes,time_elapsed_hours
0,1522242002000,23.154500,72.668081,0.000000,10.0,0,2018-03-28 13:00:02,2018-03-28,13:00:02,13,...,2,2,87,-0.258819,-0.965926,0.000000,1.000000,0.0,0.000000,0.000000
1,1522242099000,23.154457,72.668187,0.000000,10.5,1,2018-03-28 13:01:39,2018-03-28,13:01:39,13,...,39,2,87,-0.258819,-0.965926,0.104528,0.994522,97.0,1.616667,0.026944
2,1522242102000,23.154471,72.668257,0.096768,10.0,0,2018-03-28 13:01:42,2018-03-28,13:01:42,13,...,42,2,87,-0.258819,-0.965926,0.104528,0.994522,100.0,1.666667,0.027778
3,1522242103000,23.154438,72.668264,0.279494,10.0,0,2018-03-28 13:01:43,2018-03-28,13:01:43,13,...,43,2,87,-0.258819,-0.965926,0.104528,0.994522,101.0,1.683333,0.028056
4,1522242105000,23.154411,72.668269,0.000000,10.0,0,2018-03-28 13:01:45,2018-03-28,13:01:45,13,...,45,2,87,-0.258819,-0.965926,0.104528,0.994522,103.0,1.716667,0.028611

In [16]:
# Time intervals between consecutive points
df_merged['time_diff_seconds'] = df_merged['Time'].diff() / 1000  # Convert ms to seconds
df_merged['time_diff_minutes'] = df_merged['time_diff_seconds'] / 60

# Cumulative time from start
df_merged['cumulative_time_minutes'] = df_merged['time_diff_minutes'].cumsum().fillna(0)

# Time-based movement indicators
df_merged['is_stationary'] = (df_merged['Speed'] == 0).astype(int)
df_merged['stationary_duration'] = df_merged.groupby((df_merged['Speed'] != 0).cumsum())['time_diff_seconds'].cumsum()

In [17]:
df_merged.head()

,Time,Latitude,Longitude,Speed,Accuracy,Partition,datetime,date,time_hms,hour,...,minute_sin,minute_cos,time_elapsed_seconds,time_elapsed_minutes,time_elapsed_hours,time_diff_seconds,time_diff_minutes,cumulative_time_minutes,is_stationary,stationary_duration
0,1522242002000,23.154500,72.668081,0.000000,10.0,0,2018-03-28 13:00:02,2018-03-28,13:00:02,13,...,0.000000,1.000000,0.0,0.000000,0.000000,NaN,NaN,0.000000,1,NaN
1,1522242099000,23.154457,72.668187,0.000000,10.5,1,2018-03-28 13:01:39,2018-03-28,13:01:39,13,...,0.104528,0.994522,97.0,1.616667,0.026944,97.0,1.616667,1.616667,1,97.0
2,1522242102000,23.154471,72.668257,0.096768,10.0,0,2018-03-28 13:01:42,2018-03-28,13:01:42,13,...,0.104528,0.994522,100.0,1.666667,0.027778,3.0,0.050000,1.666667,0,3.0
3,1522242103000,23.154438,72.668264,0.279494,10.0,0,2018-03-28 13:01:43,2018-03-28,13:01:43,13,...,0.104528,0.994522,101.0,1.683333,0.028056,1.0,0.016667,1.683333,0,1.0
4,1522242105000,23.154411,72.668269,0.000000,10.0,0,2018-03-28 13:01:45,2018-03-28,13:01:45,13,...,0.104528,0.994522,103.0,1.716667,0.028611,2.0,0.033333,1.716667,1,3.0

In [18]:
df_merged.isnull().sum()

Time                        0
Latitude                    0
Longitude                   0
Speed                      56
Accuracy                    0
Partition                   0
datetime                    0
date                        0
time_hms                    0
hour                        0
minute                      0
second                      0
day_of_week                 0
day_of_year                 0
hour_sin                    0
hour_cos                    0
minute_sin                  0
minute_cos                  0
time_elapsed_seconds        0
time_elapsed_minutes        0
time_elapsed_hours          0
time_diff_seconds           1
time_diff_minutes           1
cumulative_time_minutes     0
is_stationary               0
stationary_duration         1
dtype: int64

In [19]:
# Handle missing timestamps
df_merged = df_merged.dropna(subset=['Time'])

# Remove duplicate timestamps
df_merged = df_merged.drop_duplicates(subset=['Time'])

# Sort by time
df_merged = df_merged.sort_values('Time').reset_index(drop=True)

# Handle outliers in time differences
time_diff_q99 = df_merged['time_diff_seconds'].quantile(0.99)
df_merged['time_diff_seconds'] = df_merged['time_diff_seconds'].clip(upper=time_diff_q99)

In [20]:
df_merged.head()

,Time,Latitude,Longitude,Speed,Accuracy,Partition,datetime,date,time_hms,hour,...,minute_sin,minute_cos,time_elapsed_seconds,time_elapsed_minutes,time_elapsed_hours,time_diff_seconds,time_diff_minutes,cumulative_time_minutes,is_stationary,stationary_duration
0,1522242002000,23.154500,72.668081,0.000000,10.0,0,2018-03-28 13:00:02,2018-03-28,13:00:02,13,...,0.000000,1.000000,0.0,0.000000,0.000000,NaN,NaN,0.000000,1,NaN
1,1522242099000,23.154457,72.668187,0.000000,10.5,1,2018-03-28 13:01:39,2018-03-28,13:01:39,13,...,0.104528,0.994522,97.0,1.616667,0.026944,2.0,1.616667,1.616667,1,97.0
2,1522242102000,23.154471,72.668257,0.096768,10.0,0,2018-03-28 13:01:42,2018-03-28,13:01:42,13,...,0.104528,0.994522,100.0,1.666667,0.027778,2.0,0.050000,1.666667,0,3.0
3,1522242103000,23.154438,72.668264,0.279494,10.0,0,2018-03-28 13:01:43,2018-03-28,13:01:43,13,...,0.104528,0.994522,101.0,1.683333,0.028056,1.0,0.016667,1.683333,0,1.0
4,1522242105000,23.154411,72.668269,0.000000,10.0,0,2018-03-28 13:01:45,2018-03-28,13:01:45,13,...,0.104528,0.994522,103.0,1.716667,0.028611,2.0,0.033333,1.716667,1,3.0

In [21]:
#df_merged.to_csv('Time_Series_Analysis.csv')

In [22]:
df_merged.columns

Index(['Time', 'Latitude', 'Longitude', 'Speed', 'Accuracy', 'Partition',
       'datetime', 'date', 'time_hms', 'hour', 'minute', 'second',
       'day_of_week', 'day_of_year', 'hour_sin', 'hour_cos', 'minute_sin',
       'minute_cos', 'time_elapsed_seconds', 'time_elapsed_minutes',
       'time_elapsed_hours', 'time_diff_seconds', 'time_diff_minutes',
       'cumulative_time_minutes', 'is_stationary', 'stationary_duration'],
      dtype='object')

In [23]:
df_merged.describe()

,Time,Latitude,Longitude,Speed,Accuracy,Partition,datetime,hour,minute,second,...,minute_sin,minute_cos,time_elapsed_seconds,time_elapsed_minutes,time_elapsed_hours,time_diff_seconds,time_diff_minutes,cumulative_time_minutes,is_stationary,stationary_duration
count,8.631000e+03,8631.000000,8631.000000,8576.000000,8631.000000,8631.000000,8631,8631.000000,8631.000000,8631.000000,...,8631.000000,8.631000e+03,8631.000000,8631.000000,8631.000000,8630.000000,8630.000000,8631.000000,8631.000000,8630.000000
mean,1.522662e+12,23.100364,72.549618,7.330915,11.603655,0.000579,2018-04-02 09:31:40.257928448,11.851582,24.756228,29.476538,...,0.262804,1.098681e-02,419498.257929,6991.637632,116.527294,1.206246,1.261456,6991.637632,0.156761,85.040477
min,1.522242e+12,23.027287,72.500938,0.000000,10.000000,0.000000,2018-03-28 13:00:02,2.000000,0.000000,0.000000,...,-1.000000,-1.000000e+00,0.000000,0.000000,0.000000,-0.860000,-0.014333,0.000000,0.000000,-0.860000
25%,1.522246e+12,23.050437,72.517798,1.150000,10.000000,0.000000,2018-03-28 14:00:12.500000,13.000000,12.000000,14.000000,...,-0.406737,-5.877853e-01,3610.500000,60.175000,1.002917,1.000000,0.016667,60.175000,0.000000,1.000000
50%,1.522849e+12,23.087091,72.528526,7.820000,10.000000,0.000000,2018-04-04 13:30:57,13.000000,21.000000,29.000000,...,0.500000,2.832769e-16,606655.000000,10110.916667,168.515278,1.000000,0.016667,10110.916667,0.000000,1.000000
75%,1.522851e+12,23.157939,72.574314,12.322578,10.000000,0.000000,2018-04-04 14:07:40.500000,13.000000,38.000000,45.000000,...,0.913545,5.877853e-01,608858.500000,10147.641667,169.127361,1.000000,0.016667,10147.641667,0.000000,2.000000
max,1.522895e+12,23.192695,72.668269,22.481009,899.999023,1.000000,2018-04-05 02:26:24,14.000000,59.000000,59.000000,...,1.000000,1.000000e+00,653182.000000,10886.366667,181.439444,2.000000,10007.653533,10886.366667,1.000000,600459.212000
std,2.866164e+08,0.055545,0.047485,5.624728,13.543428,0.024063,NaN,3.772943,16.198183,17.357488,...,0.708061,6.554167e-01,286616.417558,4776.940293,79.615672,0.418272,107.989081,4776.940293,0.363596,6479.359987

In [24]:
feature_columns = [
    # Spatial features
    'Latitude', 'Longitude', 'Speed', 'Accuracy',
    
    # Cyclical temporal features
    'hour_sin', 'hour_cos', 'minute_sin', 'minute_cos',
    'day_of_week', 'day_of_year',
    
    # Movement features
    'is_stationary', 'stationary_duration'
]

drop_columns = [
    # Redundant temporal
    'Time', 'datetime', 'date', 'time_hms', 'hour', 'minute', 'second',
    
    # Leakage features (if target is cumulative_time_minutes)
    'time_elapsed_seconds', 'time_elapsed_minutes', 'time_elapsed_hours',
    'time_diff_seconds', 'time_diff_minutes',
    
    # Administrative
    'Partition'
]

In [25]:
# Rolling statistics for speed patterns
df_merged['speed_rolling_mean_5'] = df_merged['Speed'].rolling(5).mean()
df_merged['speed_rolling_std_5'] = df_merged['Speed'].rolling(5).std()

# Distance calculations between consecutive points
#df_merged['distance_to_next'] = calculate_distance(lat1, lon1, lat2, lon2)

# Speed change indicators
df_merged['acceleration'] = df_merged['Speed'].diff()

In [26]:
def calculate_distance(lat1, lon1, lat2, lon2):
    """Haversine distance calculation"""
    import math
    
    # Handle NaN values
    if any(pd.isna([lat1, lon1, lat2, lon2])):
        return 0
    
    # Convert to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    
    # Haversine formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = (math.sin(dlat/2)**2 + 
         math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2)
    c = 2 * math.asin(math.sqrt(a))
    
    return 6371 * c  # Distance in km

df_merged['Latitude_next'] = df_merged['Latitude'].shift(-1)
df_merged['Longitude_next'] = df_merged['Longitude'].shift(-1)

df_merged['distance_to_next'] = df_merged.apply(
    lambda row: calculate_distance(
        row['Latitude'], row['Longitude'],
        row['Latitude_next'], row['Longitude_next']
    ), axis=1
)

In [27]:
# Rolling statistics for speed patterns
df_merged['speed_rolling_mean_5'] = df_merged['Speed'].rolling(5).mean()
df_merged['speed_rolling_std_5'] = df_merged['Speed'].rolling(5).std()

# Distance calculations between consecutive points
df_merged['distance_to_next'] = [
    calculate_distance(
        df_merged['Latitude'].iloc[i],     # lat1
        df_merged['Longitude'].iloc[i],    # lon1
        df_merged['Latitude'].iloc[i+1] if i+1 < len(df_merged) else df_merged['Latitude'].iloc[i],  # lat2
        df_merged['Longitude'].iloc[i+1] if i+1 < len(df_merged) else df_merged['Longitude'].iloc[i]  # lon2
    ) if i+1 < len(df_merged) else 0
    for i in range(len(df_merged))
]

# Speed change indicators
df_merged['acceleration'] = df_merged['Speed'].diff()

In [28]:
df_merged.head()

,Time,Latitude,Longitude,Speed,Accuracy,Partition,datetime,date,time_hms,hour,...,time_diff_minutes,cumulative_time_minutes,is_stationary,stationary_duration,speed_rolling_mean_5,speed_rolling_std_5,acceleration,Latitude_next,Longitude_next,distance_to_next
0,1522242002000,23.154500,72.668081,0.000000,10.0,0,2018-03-28 13:00:02,2018-03-28,13:00:02,13,...,NaN,0.000000,1,NaN,NaN,NaN,NaN,23.154457,72.668187,0.011826
1,1522242099000,23.154457,72.668187,0.000000,10.5,1,2018-03-28 13:01:39,2018-03-28,13:01:39,13,...,1.616667,1.616667,1,97.0,NaN,NaN,0.000000,23.154471,72.668257,0.007333
2,1522242102000,23.154471,72.668257,0.096768,10.0,0,2018-03-28 13:01:42,2018-03-28,13:01:42,13,...,0.050000,1.666667,0,3.0,NaN,NaN,0.096768,23.154438,72.668264,0.003807
3,1522242103000,23.154438,72.668264,0.279494,10.0,0,2018-03-28 13:01:43,2018-03-28,13:01:43,13,...,0.016667,1.683333,0,1.0,NaN,NaN,0.182726,23.154411,72.668269,0.003017
4,1522242105000,23.154411,72.668269,0.000000,10.0,0,2018-03-28 13:01:45,2018-03-28,13:01:45,13,...,0.033333,1.716667,1,3.0,0.075252,0.121621,-0.279494,23.154430,72.668261,0.002266

In [29]:
df_merged.columns

Index(['Time', 'Latitude', 'Longitude', 'Speed', 'Accuracy', 'Partition',
       'datetime', 'date', 'time_hms', 'hour', 'minute', 'second',
       'day_of_week', 'day_of_year', 'hour_sin', 'hour_cos', 'minute_sin',
       'minute_cos', 'time_elapsed_seconds', 'time_elapsed_minutes',
       'time_elapsed_hours', 'time_diff_seconds', 'time_diff_minutes',
       'cumulative_time_minutes', 'is_stationary', 'stationary_duration',
       'speed_rolling_mean_5', 'speed_rolling_std_5', 'acceleration',
       'Latitude_next', 'Longitude_next', 'distance_to_next'],
      dtype='object')

In [30]:
df_merged.isnull().sum()

Time                         0
Latitude                     0
Longitude                    0
Speed                       55
Accuracy                     0
Partition                    0
datetime                     0
date                         0
time_hms                     0
hour                         0
minute                       0
second                       0
day_of_week                  0
day_of_year                  0
hour_sin                     0
hour_cos                     0
minute_sin                   0
minute_cos                   0
time_elapsed_seconds         0
time_elapsed_minutes         0
time_elapsed_hours           0
time_diff_seconds            1
time_diff_minutes            1
cumulative_time_minutes      0
is_stationary                0
stationary_duration          1
speed_rolling_mean_5       105
speed_rolling_std_5        105
acceleration                68
Latitude_next                1
Longitude_next               1
distance_to_next             0
dtype: int64

In [31]:
# Remove all rows with any missing values
df_clean = df_merged.dropna(inplace=True)

In [32]:
df_merged.isnull().sum()

Time                       0
Latitude                   0
Longitude                  0
Speed                      0
Accuracy                   0
Partition                  0
datetime                   0
date                       0
time_hms                   0
hour                       0
minute                     0
second                     0
day_of_week                0
day_of_year                0
hour_sin                   0
hour_cos                   0
minute_sin                 0
minute_cos                 0
time_elapsed_seconds       0
time_elapsed_minutes       0
time_elapsed_hours         0
time_diff_seconds          0
time_diff_minutes          0
cumulative_time_minutes    0
is_stationary              0
stationary_duration        0
speed_rolling_mean_5       0
speed_rolling_std_5        0
acceleration               0
Latitude_next              0
Longitude_next             0
distance_to_next           0
dtype: int64

In [33]:
df_merged.head()

,Time,Latitude,Longitude,Speed,Accuracy,Partition,datetime,date,time_hms,hour,...,time_diff_minutes,cumulative_time_minutes,is_stationary,stationary_duration,speed_rolling_mean_5,speed_rolling_std_5,acceleration,Latitude_next,Longitude_next,distance_to_next
4,1522242105000,23.154411,72.668269,0.000000,10.0,0,2018-03-28 13:01:45,2018-03-28,13:01:45,13,...,0.033333,1.716667,1,3.0,0.075252,0.121621,-0.279494,23.154430,72.668261,0.002266
5,1522242107000,23.154430,72.668261,0.000000,10.0,0,2018-03-28 13:01:47,2018-03-28,13:01:47,13,...,0.033333,1.750000,1,5.0,0.075252,0.121621,0.000000,23.154436,72.668241,0.002131
6,1522242109000,23.154436,72.668241,1.302247,10.0,0,2018-03-28 13:01:49,2018-03-28,13:01:49,13,...,0.033333,1.783333,0,2.0,0.335702,0.552234,1.302247,23.154448,72.668217,0.002826
7,1522242111000,23.154448,72.668217,1.910134,10.0,0,2018-03-28 13:01:51,2018-03-28,13:01:51,13,...,0.033333,1.816667,0,2.0,0.698375,0.863704,0.607887,23.154467,72.668189,0.003535
8,1522242113000,23.154467,72.668189,0.000000,10.0,0,2018-03-28 13:01:53,2018-03-28,13:01:53,13,...,0.033333,1.850000,1,4.0,0.642476,0.905619,-1.910134,23.154484,72.668157,0.003730

In [34]:
df_merged.columns

Index(['Time', 'Latitude', 'Longitude', 'Speed', 'Accuracy', 'Partition',
       'datetime', 'date', 'time_hms', 'hour', 'minute', 'second',
       'day_of_week', 'day_of_year', 'hour_sin', 'hour_cos', 'minute_sin',
       'minute_cos', 'time_elapsed_seconds', 'time_elapsed_minutes',
       'time_elapsed_hours', 'time_diff_seconds', 'time_diff_minutes',
       'cumulative_time_minutes', 'is_stationary', 'stationary_duration',
       'speed_rolling_mean_5', 'speed_rolling_std_5', 'acceleration',
       'Latitude_next', 'Longitude_next', 'distance_to_next'],
      dtype='object')

In [35]:
y = df_merged['cumulative_time_minutes']  # RECOMMENDED - Total trip tim

In [36]:


# --- CORRECTED Feature Lists (based on your DataFrame) ---
# RobustScaler for outlier-prone features
robust_features = ['Latitude', 'Longitude', 'Speed', 'distance_to_next', 'Accuracy', 'acceleration']

# StandardScaler for rolling statistics
standard_features = ['speed_rolling_mean_5', 'speed_rolling_std_5']

# MinMaxScaler for bounded features
minmax_features = ['day_of_week', 'day_of_year', 'cumulative_time_minutes']

# --- Get a list of the columns that are actually in the DataFrame ---
available_cols = list(df_merged.columns)

# Filter each feature list to keep only the available columns
# This step makes the code robust, even if a column is missing in the future.
robust_features_present = [col for col in robust_features if col in available_cols]
standard_features_present = [col for col in standard_features if col in available_cols]
minmax_features_present = [col for col in minmax_features if col in available_cols]

# Combine all features that will be transformed
all_present_features = set(robust_features_present + standard_features_present + minmax_features_present)


# --- Create the ColumnTransformer with the valid column lists ---
preprocessor = ColumnTransformer(
    transformers=[
        ('robust', RobustScaler(), robust_features_present),
        ('standard', StandardScaler(), standard_features_present),
        ('minmax', MinMaxScaler(), minmax_features_present)
    ],
    remainder='passthrough'  # Keep all other columns untouched
)

# Apply the transformations
df_merged_scaled_array = preprocessor.fit_transform(df_merged)

# --- Convert back to a DataFrame with correct column names ---
# Find columns that were not transformed
passthrough_columns = [col for col in df_merged.columns if col not in all_present_features]

# The new column order is the one defined by the ColumnTransformer
new_column_order = robust_features_present + standard_features_present + minmax_features_present + passthrough_columns

# Create the new scaled DataFrame
df_merged_scaled = pd.DataFrame(df_merged_scaled_array, columns=new_column_order, index=df_merged.index)

print("Scaling complete!")
# You can now use the `df_merged_scaled` DataFrame
print(df_merged_scaled.head())

Scaling complete!
   Latitude Longitude     Speed distance_to_next Accuracy acceleration  \
4  0.625517  2.458853 -0.703412        -0.509259      0.0    -0.834102
5  0.625693  2.458707 -0.703412        -0.520161      0.0          0.0
6  0.625743  2.458355 -0.586837        -0.464223      0.0     3.886331
7  0.625861  2.457932  -0.53242        -0.407091      0.0     1.814133
8  0.626037  2.457443 -0.703412        -0.391391      0.0    -5.700464

  speed_rolling_mean_5 speed_rolling_std_5 day_of_week day_of_year  ...  \
4            -1.299256           -0.655799         0.0         0.0  ...
5            -1.299256           -0.655799         0.0         0.0  ...
6            -1.252661            0.185206         0.0         0.0  ...
7            -1.187777            0.793519         0.0         0.0  ...
8            -1.197778            0.875381         0.0         0.0  ...

  minute_cos time_elapsed_seconds time_elapsed_minutes time_elapsed_hours  \
4   0.994522                103.0             1.716667           0.028611
5   0.994522                105.0                 1.75           0.029167
6   0.994522                107.0             1.783333           0.029722
7   0.994522                109.0             1.816667           0.030278
8   0.994522                111.0                 1.85           0.030833

  time_diff_seconds time_diff_minutes is_stationary stationary_duration  \
4               2.0          0.033333             1                 3.0
5               2.0          0.033333             1                 5.0
6               2.0          0.033333             0                 2.0
7               2.0          0.033333             0                 2.0
8               2.0          0.033333             1                 4.0

  Latitude_next Longitude_next
4      23.15443      72.668261
5     23.154436      72.668241
6     23.154448      72.668217
7     23.154467      72.668189
8     23.154484      72.668157

[5 rows x 32 columns]

In [42]:
df_merged.columns

Index(['Time', 'Latitude', 'Longitude', 'Speed', 'Accuracy', 'Partition',
       'datetime', 'date', 'time_hms', 'hour', 'minute', 'second',
       'day_of_week', 'day_of_year', 'hour_sin', 'hour_cos', 'minute_sin',
       'minute_cos', 'time_elapsed_seconds', 'time_elapsed_minutes',
       'time_elapsed_hours', 'time_diff_seconds', 'time_diff_minutes',
       'cumulative_time_minutes', 'is_stationary', 'stationary_duration',
       'speed_rolling_mean_5', 'speed_rolling_std_5', 'acceleration',
       'Latitude_next', 'Longitude_next', 'distance_to_next'],
      dtype='object')

In [ ]:

# Define feature groups based on data characteristics
robust_features = ['Latitude', 'Longitude', 'Speed', 'Accuracy', 'acceleration', 'distance_to_next']
standard_features = ['speed_rolling_mean_5', 'speed_rolling_std_5', 'stationary_duration']
minmax_features = ['day_of_week', 'day_of_year', 'cumulative_time_minutes']
# No scaling needed: ['hour_sin', 'hour_cos', 'minute_sin', 'minute_cos', 'is_stationary']

# Initialize scalers
robust_scaler = RobustScaler()
standard_scaler = StandardScaler()
minmax_scaler = MinMaxScaler()

# Apply scaling transformations
print("Applying RobustScaler to GPS and movement data...")
df_merged[robust_features] = robust_scaler.fit_transform(df_merged[robust_features])

print("Applying StandardScaler to rolling statistics...")
df_merged[standard_features] = standard_scaler.fit_transform(df_merged[standard_features])

print("Applying MinMaxScaler to temporal features...")
df_merged[minmax_features] = minmax_scaler.fit_transform(df_merged[minmax_features])

print("Scaling complete! Data is now ready for model training.")

# Verify scaling results
print("\nFeature ranges after scaling:")
print(df_merged[robust_features + standard_features + minmax_features].describe())

In [44]:
df_final.head()

,Latitude,Longitude,Speed,Accuracy,day_of_week,day_of_year,hour_sin,hour_cos,minute_sin,minute_cos,cumulative_time_minutes,is_stationary,stationary_duration,speed_rolling_mean_5,speed_rolling_std_5,acceleration,distance_to_next
4,23.154411,72.668269,0.000000,10.0,2,87,-0.258819,-0.965926,0.104528,0.994522,1.716667,1,3.0,0.075252,0.121621,-0.279494,0.002266
5,23.154430,72.668261,0.000000,10.0,2,87,-0.258819,-0.965926,0.104528,0.994522,1.750000,1,5.0,0.075252,0.121621,0.000000,0.002131
6,23.154436,72.668241,1.302247,10.0,2,87,-0.258819,-0.965926,0.104528,0.994522,1.783333,0,2.0,0.335702,0.552234,1.302247,0.002826
7,23.154448,72.668217,1.910134,10.0,2,87,-0.258819,-0.965926,0.104528,0.994522,1.816667,0,2.0,0.698375,0.863704,0.607887,0.003535
8,23.154467,72.668189,0.000000,10.0,2,87,-0.258819,-0.965926,0.104528,0.994522,1.850000,1,4.0,0.642476,0.905619,-1.910134,0.003730

In [39]:
# Create training data
X = df_merged[feature_columns]
y = df_merged[target_column]

In [40]:
X

,Latitude,Longitude,Speed,distance_to_next,Accuracy,acceleration,speed_rolling_mean_5,speed_rolling_std_5,is_stationary,stationary_duration,hour_sin,hour_cos,minute_sin,minute_cos,day_of_week,day_of_year
4,23.154411,72.668269,0.000000,0.002266,10.0,-0.279494,0.075252,0.121621,1,3.0,-0.258819,-0.965926,0.104528,0.994522,2,87
5,23.154430,72.668261,0.000000,0.002131,10.0,0.000000,0.075252,0.121621,1,5.0,-0.258819,-0.965926,0.104528,0.994522,2,87
6,23.154436,72.668241,1.302247,0.002826,10.0,1.302247,0.335702,0.552234,0,2.0,-0.258819,-0.965926,0.104528,0.994522,2,87
7,23.154448,72.668217,1.910134,0.003535,10.0,0.607887,0.698375,0.863704,0,2.0,-0.258819,-0.965926,0.104528,0.994522,2,87
8,23.154467,72.668189,0.000000,0.003730,10.0,-1.910134,0.642476,0.905619,1,4.0,-0.258819,-0.965926,0.104528,0.994522,2,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8625,23.135914,72.542336,8.190000,0.008673,10.0,-0.370000,8.840000,0.574239,0,1.0,0.500000,0.866025,0.406737,-0.913545,3,95
8626,23.135989,72.542314,8.070000,0.007563,10.0,-0.120000,8.514000,0.400287,0,1.0,0.500000,0.866025,0.406737,-0.913545,3,95
8627,23.136055,72.542299,7.600000,0.006880,10.0,-0.470000,8.220000,0.428660,0,1.0,0.500000,0.866025,0.406737,-0.913545,3,95
8628,23.136116,72.542287,7.100000,0.006795,10.0,-0.500000,7.904000,0.565358,0,1.0,0.500000,0.866025,0.406737,-0.913545,3,95
8629,23.136177,72.542288,6.840000,0.006349,10.0,-0.260000,7.560000,0.589194,0,1.0,0.500000,0.866025,0.406737,-0.913545,3,95

In [43]:
# Define features to keep
final_features = [
    'Latitude', 'Longitude', 'Speed', 'Accuracy',
    'day_of_week', 'day_of_year', 
    'hour_sin', 'hour_cos', 'minute_sin', 'minute_cos',
    'cumulative_time_minutes', 'is_stationary', 'stationary_duration',
    'speed_rolling_mean_5', 'speed_rolling_std_5', 
    'acceleration', 'distance_to_next'
]

# Drop redundant features
df_final = df_merged[final_features].copy()

df_final.to_csv("Final_ETA.csv")